SELECT *
FROM BOOKINGS
JOIN USERS ON BOOKINGS.user_id = USERS.user_id;

SELECT *
FROM PROPERTIES
LEFT JOIN REVIEWS ON PROPERTIES.property_id = REVIEWS.property_id;

SELECT * 
FROM USERS 
LEFT JOIN BOOKINGS ON USERS.user_id = BOOKINGS.user_id

UNION

SELECT * 
FROM USERS 
RIGHT JOIN BOOKINGS ON USERS.user_id = BOOKINGS.user_id;